import {
  ActivityAction,
  DashboardSummary,
  Invoice,
  ModelStatus,
  PortalInvoice,
} from "@/lib/api";

const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();

export const demoSummary: DashboardSummary = {
  revenue_at_risk_cents: 184700,
  revenue_recovered_cents: 96800,
  revenue_exhausted_cents: 32100,
  recovery_rate: 0.751,
  top_failure_reasons: [
    { reason: "insufficient_funds", count: 18 },
    { reason: "expired_card", count: 11 },
    { reason: "do_not_honor", count: 8 },
    { reason: "try_again_later", count: 6 },
    { reason: "processing_error", count: 4 },
  ],
  pipeline_counts: {
    PENDING: 14,
    SCHEDULED_RETRY: 9,
    DUNNING_ACTIVE: 7,
    FRAUD_REVIEW: 2,
    RECOVERED: 31,
    FAILED_EXHAUSTED: 6,
  },
  recent_actions: [],
};

export const demoInvoices: Invoice[] = [
  {
    id: "demo-1",
    invoice_id: "in_2048",
    customer_name: "Maya Patel",
    customer_email: "maya.patel@example.com",
    amount_due_cents: 9900,
    raw_decline_code: "insufficient_funds",
    iso_8583_code: "51",
    failure_type: "SOFT_DECLINE",
    status: "DUNNING_ACTIVE",
    attempt_count: 2,
    next_action_scheduled_at: minutesAgo(-360),
    recovered_at: null,
    created_at: minutesAgo(42),
  },
  {
    id: "demo-2",
    invoice_id: "in_2047",
    customer_name: "Jordan Kim",
    customer_email: "jordan.kim@example.com",
    amount_due_cents: 49900,
    raw_decline_code: "expired_card",
    iso_8583_code: "54",
    failure_type: "HARD_DECLINE",
    status: "PENDING",
    attempt_count: 1,
    next_action_scheduled_at: null,
    recovered_at: null,
    created_at: minutesAgo(78),
  },
  {
    id: "demo-3",
    invoice_id: "in_2046",
    customer_name: "Sofia Garcia",
    customer_email: "sofia.garcia@example.com",
    amount_due_cents: 19900,
    raw_decline_code: "do_not_honor",
    iso_8583_code: "05",
    failure_type: "SOFT_DECLINE",
    status: "SCHEDULED_RETRY",
    attempt_count: 2,
    next_action_scheduled_at: minutesAgo(-95),
    recovered_at: null,
    created_at: minutesAgo(115),
  },
  {
    id: "demo-4",
    invoice_id: "in_2045",
    customer_name: "Liam Chen",
    customer_email: "liam.chen@example.com",
    amount_due_cents: 4900,
    raw_decline_code: "try_again_later",
    iso_8583_code: "91",
    failure_type: "SOFT_DECLINE",
    status: "FRAUD_REVIEW",
    attempt_count: 3,
    next_action_scheduled_at: null,
    recovered_at: null,
    created_at: minutesAgo(164),
  },
  {
    id: "demo-5",
    invoice_id: "in_2044",
    customer_name: "Priya Sharma",
    customer_email: "priya.sharma@example.com",
    amount_due_cents: 99900,
    raw_decline_code: "insufficient_funds",
    iso_8583_code: "51",
    failure_type: "SOFT_DECLINE",
    status: "PENDING",
    attempt_count: 1,
    next_action_scheduled_at: null,
    recovered_at: null,
    created_at: minutesAgo(205),
  },
  {
    id: "demo-6",
    invoice_id: "in_2043",
    customer_name: "Elena Novak",
    customer_email: "elena.novak@example.com",
    amount_due_cents: 1900,
    raw_decline_code: "processing_error",
    iso_8583_code: "96",
    failure_type: "SOFT_DECLINE",
    status: "DUNNING_ACTIVE",
    attempt_count: 2,
    next_action_scheduled_at: minutesAgo(-720),
    recovered_at: null,
    created_at: minutesAgo(251),
  },
  {
    id: "demo-7",
    invoice_id: "in_2042",
    customer_name: "Noah Reyes",
    customer_email: "noah.reyes@example.com",
    amount_due_cents: 19900,
    raw_decline_code: "expired_card",
    iso_8583_code: "54",
    failure_type: "HARD_DECLINE",
    status: "FAILED_EXHAUSTED",
    attempt_count: 4,
    next_action_scheduled_at: null,
    recovered_at: null,
    created_at: minutesAgo(310),
  },
  {
    id: "demo-8",
    invoice_id: "in_2041",
    customer_name: "Zara Khan",
    customer_email: "zara.khan@example.com",
    amount_due_cents: 9900,
    raw_decline_code: "insufficient_funds",
    iso_8583_code: "51",
    failure_type: "SOFT_DECLINE",
    status: "RECOVERED",
    attempt_count: 2,
    next_action_scheduled_at: null,
    recovered_at: minutesAgo(340),
    created_at: minutesAgo(390),
  },
];

export const demoActivity: ActivityAction[] = [
  {
    id: "activity-1",
    action_type: "CARD_UPDATED",
    channel: "portal",
    is_successful: true,
    created_at: minutesAgo(8),
    invoice_ref: "in_2041",
    customer_name: "Zara Khan",
    amount_due_cents: 9900,
  },
  {
    id: "activity-2",
    action_type: "DUNNING_EMAIL",
    channel: "email",
    is_successful: true,
    created_at: minutesAgo(24),
    invoice_ref: "in_2048",
    customer_name: "Maya Patel",
    amount_due_cents: 9900,
  },
  {
    id: "activity-3",
    action_type: "HEADLESS_RETRY",
    channel: "stripe",
    is_successful: false,
    created_at: minutesAgo(51),
    invoice_ref: "in_2046",
    customer_name: "Sofia Garcia",
    amount_due_cents: 19900,
  },
  {
    id: "activity-4",
    action_type: "FRAUD_FLAGGED",
    channel: "rules",
    is_successful: null,
    created_at: minutesAgo(73),
    invoice_ref: "in_2045",
    customer_name: "Liam Chen",
    amount_due_cents: 4900,
  },
];

export const demoModelStatus: ModelStatus = {
  trained: true,
  enabled: true,
  active: true,
  is_synthetic: true,
  trained_at: "2026-09-12T09:30:00.000Z",
  n_samples: 2400,
  test_auc: 0.84,
  test_accuracy: 0.79,
  test_brier_score: 0.16,
};

export const demoPortalInvoice: PortalInvoice = {
  already_recovered: false,
  tenant_name: "Acme SaaS Inc",
  customer_name: "Maya Patel",
  amount_due_cents: 9900,
  currency: "usd",
  invoice_ref: "in_2048",
};